import type { NextPage } from "next";
import Head from "next/head";
import type { KeyboardEvent } from "react";
import { useState } from "react";
import { toast } from "react-toastify";

interface Weather {
  name: string;
  sys: { country: string };
  weather: [
    {
      main: string;
    }
  ];
  main: {
    temp: number;
  };
  cod: any;
}

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const [weather, setWeather] = useState<Weather | null>(null);

  const handleKeyUp = async (e: KeyboardEvent) => {
    if (e.key === "Enter") {
      try {
        const res = await fetch(`/api/weather?loc=${encodeURI(search)}`);
        const body = await res.json();

        // Intentionally using abstract equality since this value
        // seems to vary from number to string
        if (body.cod == "200") {
          setSearch("");
          setWeather(body);
        } else if (body.cod == "404") {
          console.log("toast!");
          toast.error(
            "Location not found. If you think this is a mistake, try changing the text and see if it works."
          );
        }
      } catch (error) {
        console.error(error);
        toast.error(
          "An error happened while trying to get weather data for this location. Please try again later!"
        );
      }
    }
  };

  return (
    <div className="container">
      <Head>
        <title>
          {weather
            ? `Weather - ${weather.name}, ${weather.sys.country}`
            : "Where will we go today?"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <input
          value={search}
          placeholder="Location..."
          onKeyUp={handleKeyUp}
          onChange={(e) => setSearch(e.target.value)}
        />

        {weather && (
          <div className="weather">
            <h1>{Math.round(weather.main.temp) - 273}&#176; C</h1>
            <h2>{weather.weather[0].main}</h2>
            <p>
              {weather.name}, {weather.sys.country}
            </p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
